/*
 * Copyright 2017 José A. Pacheco Ondoño - joanpaon@gmail.com.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.japo.java.views;

import java.util.Properties;
import javax.swing.JFrame;
import org.japo.java.controllers.Controller;
import org.japo.java.models.Model;
import org.japo.java.libraries.UtilesApp;

/**
 *
 * @author José A. Pacheco Ondoño - joanpaon@gmail.com
 */
public class View extends javax.swing.JFrame {

    // Fichero Propiedades
    public static final String FICHERO = "view.properties";

    // Referencias
    private Model model;
    private Controller control;
    private Properties prpView;

    // Constructor
    public View() {
        // Inicializacion Anterior
        initBefore();

        // Creación Vista
        initComponents();

        // Inicializacion Posterior
        initAfter();
    }

    public Model getModel() {
        return model;
    }

    public void setModel(Model model) {
        this.model = model;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.ButtonGroup();
        dtpMain = new javax.swing.JDesktopPane();
        infRotulo = new javax.swing.JInternalFrame();
        pnlRotulo = new javax.swing.JPanel();
        lblRotulo = new javax.swing.JLabel();
        infAjuste = new javax.swing.JInternalFrame();
        pnlAjuste = new javax.swing.JPanel();
        sldRojo = new javax.swing.JSlider();
        lblRojo = new javax.swing.JLabel();
        sldVerde = new javax.swing.JSlider();
        lblVerde = new javax.swing.JLabel();
        sldAzul = new javax.swing.JSlider();
        lblAzul = new javax.swing.JLabel();
        rbtFrente = new javax.swing.JRadioButton();
        lblFrente = new javax.swing.JLabel();
        rbtFondo = new javax.swing.JRadioButton();
        lblFondo = new javax.swing.JLabel();
        infControl = new javax.swing.JInternalFrame();
        pnlControl = new javax.swing.JPanel();
        btnImportar = new javax.swing.JButton();
        btnExportar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestión Color Rótulo");
        setExtendedState(JFrame.MAXIMIZED_BOTH);

        dtpMain.setOpaque(false);
        dtpMain.setSelectedFrame(infControl);

        infRotulo.setResizable(true);
        infRotulo.setTitle("Rótulo");
        infRotulo.setMinimumSize(new java.awt.Dimension(620, 200));
        infRotulo.setNormalBounds(new java.awt.Rectangle(10, 10, 620, 200));
        infRotulo.setPreferredSize(new java.awt.Dimension(620, 200));
        infRotulo.setVisible(true);
        infRotulo.getContentPane().setLayout(new java.awt.GridBagLayout());

        lblRotulo.setBackground(java.awt.Color.white);
        lblRotulo.setFont(new java.awt.Font("Calibri", 0, 60)); // NOI18N
        lblRotulo.setForeground(java.awt.Color.black);
        lblRotulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRotulo.setText("Feliz Verano");
        lblRotulo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        lblRotulo.setOpaque(true);

        javax.swing.GroupLayout pnlRotuloLayout = new javax.swing.GroupLayout(pnlRotulo);
        pnlRotulo.setLayout(pnlRotuloLayout);
        pnlRotuloLayout.setHorizontalGroup(
            pnlRotuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRotuloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRotulo, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlRotuloLayout.setVerticalGroup(
            pnlRotuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRotuloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRotulo, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        infRotulo.getContentPane().add(pnlRotulo, new java.awt.GridBagConstraints());

        dtpMain.add(infRotulo);
        infRotulo.setBounds(10, 10, 620, 200);

        infAjuste.setResizable(true);
        infAjuste.setTitle("Ajuste");
        infAjuste.setMinimumSize(new java.awt.Dimension(620, 350));
        infAjuste.setNormalBounds(new java.awt.Rectangle(10, 220, 620, 350));
        infAjuste.setPreferredSize(new java.awt.Dimension(620, 350));
        infAjuste.setVisible(true);
        infAjuste.getContentPane().setLayout(new java.awt.GridBagLayout());

        sldRojo.setMaximum(255);
        sldRojo.setValue(0);
        sldRojo.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldRojoStateChanged(evt);
            }
        });

        lblRojo.setBackground(java.awt.Color.red);
        lblRojo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblRojo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRojo.setText("0");
        lblRojo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        lblRojo.setOpaque(true);
        lblRojo.setPreferredSize(new java.awt.Dimension(50, 50));

        sldVerde.setMaximum(255);
        sldVerde.setValue(0);
        sldVerde.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldVerdeStateChanged(evt);
            }
        });

        lblVerde.setBackground(java.awt.Color.green);
        lblVerde.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblVerde.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVerde.setText("0");
        lblVerde.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        lblVerde.setOpaque(true);
        lblVerde.setPreferredSize(new java.awt.Dimension(50, 50));

        sldAzul.setMaximum(255);
        sldAzul.setValue(0);
        sldAzul.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldAzulStateChanged(evt);
            }
        });

        lblAzul.setBackground(java.awt.Color.blue);
        lblAzul.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblAzul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAzul.setText("0");
        lblAzul.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        lblAzul.setOpaque(true);
        lblAzul.setPreferredSize(new java.awt.Dimension(50, 50));

        bg.add(rbtFrente);
        rbtFrente.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        rbtFrente.setSelected(true);
        rbtFrente.setText("Foreground");
        rbtFrente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtFrenteActionPerformed(evt);
            }
        });

        lblFrente.setBackground(java.awt.Color.black);
        lblFrente.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblFrente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFrente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        lblFrente.setOpaque(true);
        lblFrente.setPreferredSize(new java.awt.Dimension(50, 50));

        bg.add(rbtFondo);
        rbtFondo.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        rbtFondo.setText("Background");
        rbtFondo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtFondoActionPerformed(evt);
            }
        });

        lblFondo.setBackground(java.awt.Color.white);
        lblFondo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblFondo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFondo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        lblFondo.setOpaque(true);
        lblFondo.setPreferredSize(new java.awt.Dimension(50, 50));

        javax.swing.GroupLayout pnlAjusteLayout = new javax.swing.GroupLayout(pnlAjuste);
        pnlAjuste.setLayout(pnlAjusteLayout);
        pnlAjusteLayout.setHorizontalGroup(
            pnlAjusteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAjusteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAjusteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sldRojo, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sldVerde, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sldAzul, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbtFrente, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbtFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAjusteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRojo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblVerde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAzul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFrente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlAjusteLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {rbtFondo, rbtFrente, sldAzul, sldRojo, sldVerde});

        pnlAjusteLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblAzul, lblFondo, lblFrente, lblRojo, lblVerde});

        pnlAjusteLayout.setVerticalGroup(
            pnlAjusteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAjusteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAjusteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sldRojo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRojo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAjusteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sldVerde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblVerde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAjusteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sldAzul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAzul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAjusteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFrente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbtFrente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAjusteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbtFondo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlAjusteLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblRojo, sldAzul, sldRojo, sldVerde});

        pnlAjusteLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblFrente, rbtFrente});

        pnlAjusteLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblFondo, rbtFondo});

        infAjuste.getContentPane().add(pnlAjuste, new java.awt.GridBagConstraints());

        dtpMain.add(infAjuste);
        infAjuste.setBounds(10, 220, 620, 350);

        infControl.setResizable(true);
        infControl.setTitle("Control");
        infControl.setMinimumSize(new java.awt.Dimension(620, 150));
        infControl.setNormalBounds(new java.awt.Rectangle(10, 580, 620, 150));
        infControl.setPreferredSize(new java.awt.Dimension(620, 150));
        infControl.setVisible(true);
        infControl.getContentPane().setLayout(new java.awt.GridBagLayout());

        btnImportar.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        btnImportar.setText("Importar");
        btnImportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportarActionPerformed(evt);
            }
        });

        btnExportar.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        btnExportar.setText("Exportar");
        btnExportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlControlLayout = new javax.swing.GroupLayout(pnlControl);
        pnlControl.setLayout(pnlControlLayout);
        pnlControlLayout.setHorizontalGroup(
            pnlControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlControlLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(btnImportar, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(btnExportar, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlControlLayout.setVerticalGroup(
            pnlControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlControlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnImportar)
                    .addComponent(btnExportar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        infControl.getContentPane().add(pnlControl, new java.awt.GridBagConstraints());

        dtpMain.add(infControl);
        infControl.setBounds(10, 580, 620, 150);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dtpMain, javax.swing.GroupLayout.DEFAULT_SIZE, 931, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dtpMain)
        );

        setSize(new java.awt.Dimension(949, 876));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void sldRojoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldRojoStateChanged
        control.procesarColor(evt);
    }//GEN-LAST:event_sldRojoStateChanged

    private void sldVerdeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldVerdeStateChanged
        control.procesarColor(evt);
    }//GEN-LAST:event_sldVerdeStateChanged

    private void sldAzulStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldAzulStateChanged
        control.procesarColor(evt);
    }//GEN-LAST:event_sldAzulStateChanged

    private void rbtFrenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtFrenteActionPerformed
        control.procesarFrenteFondo(evt);
    }//GEN-LAST:event_rbtFrenteActionPerformed

    private void rbtFondoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtFondoActionPerformed
        control.procesarFrenteFondo(evt);
    }//GEN-LAST:event_rbtFondoActionPerformed

    private void btnImportarActionPerformed(java.awt.event.ActionEvent evt) {                                            
        control.procesarImportacion(evt);
    }                                           

    private void btnExportarActionPerformed(java.awt.event.ActionEvent evt) {                                            
        control.procesarExportacion(evt);
    }                                           

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bg;
    private javax.swing.JButton btnExportar;
    private javax.swing.JButton btnImportar;
    private javax.swing.JDesktopPane dtpMain;
    private javax.swing.JInternalFrame infAjuste;
    private javax.swing.JInternalFrame infControl;
    private javax.swing.JInternalFrame infRotulo;
    public javax.swing.JLabel lblAzul;
    public javax.swing.JLabel lblFondo;
    public javax.swing.JLabel lblFrente;
    public javax.swing.JLabel lblRojo;
    public javax.swing.JLabel lblRotulo;
    public javax.swing.JLabel lblVerde;
    private javax.swing.JPanel pnlAjuste;
    private javax.swing.JPanel pnlControl;
    private javax.swing.JPanel pnlRotulo;
    public javax.swing.JRadioButton rbtFondo;
    public javax.swing.JRadioButton rbtFrente;
    public javax.swing.JSlider sldAzul;
    public javax.swing.JSlider sldRojo;
    public javax.swing.JSlider sldVerde;
    // End of variables declaration//GEN-END:variables

    // Inicializacion Anterior
    private void initBefore() {
        // Crear Modelo
        model = new Model();

        // Crear Controlador
        control = new Controller(model, this);

        // Cargar Propiedades Vista
        prpView = UtilesApp.cargarPropiedades(FICHERO);

        // Restaurar Estado
        control.restaurarEstadoVista(this, prpView);
    }

    // Inicializacion Posterior
    private void initAfter() {
        // Modelo > Vista
        control.sincronizarModeloVista(model, this);
        
        // Enfocar Control Inicial
        btnImportar.requestFocus();
    }
}
